name: snitch
description: Just A Simple Logger
version: 1.0.0
repository: https://github.com/warioddly/snitch/tree/main/packages/snitch
publish_to: https://pub.dev

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
