name: Deploy 

on:
  push:
    branches: [ "main" ]

jobs:
  dependencies:
    name: Build 
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"
          channel: 'stable'
          cache: true
    
      - name: Run Flutter build
        run: |
          cd ./packages/snitch_inspector/
          ls
          flutter config --enable-web
          flutter pub get
          flutter build web --release --wasm --base-href="/snitch/"

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          publish_dir: ./packages/snitch_inspector/build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'
